# Generated by Django 2.2.7 on 2019-11-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdmonCuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.CharField(max_length=254)),
                ('fin', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puestos_d', models.IntegerField(default=4)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tarifa', models.IntegerField(default=0)),
                ('enCurso', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmonCuentas.Perfil')),
                ('ruta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Viajes.Ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmonCuentas.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadPuestos', models.IntegerField(default=1)),
                ('estado', models.BooleanField(default=True)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmonCuentas.Perfil')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Viajes.Viaje')),
            ],
        ),
    ]
