# Generated by Django 2.2.7 on 2019-11-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='parada',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
