# Generated by Django 2.2.7 on 2019-11-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0003_viaje_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viajes.Viaje'),
        ),
    ]
