# Generated by Django 2.2.7 on 2019-11-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdmonCuentas', '0002_auto_20191117_1611'),
        ('Viajes', '0002_reserva_parada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('motivacion', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('agradecimiento', models.CharField(blank=True, max_length=300, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmonCuentas.UsuarioTopSeat')),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('respuesta', models.CharField(blank=True, max_length=300, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('clienteAcusado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acusado', to='AdmonCuentas.UsuarioTopSeat')),
                ('clienteAfectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afectado', to='AdmonCuentas.UsuarioTopSeat')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viajes.Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia', models.CharField(max_length=300)),
                ('contexto', models.CharField(max_length=300)),
                ('respuesta', models.CharField(blank=True, max_length=300, null=True)),
                ('respondida', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmonCuentas.UsuarioTopSeat')),
            ],
        ),
        migrations.CreateModel(
            name='EventoMayor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('justificacion', models.CharField(max_length=500)),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.Queja')),
            ],
        ),
    ]
