# Generated by Django 2.2.7 on 2019-11-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmonCuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotopseat',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Pasajero'), (2, 'Conductor'), (3, 'Asistente')], default=1),
        ),
    ]
