# Generated by Django 2.2.7 on 2019-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmonCuentas', '0002_auto_20191117_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotopseat',
            name='fotoPerfil',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
