# Generated by Django 2.2.6 on 2019-10-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='usuario',
        ),
    ]
