# Generated by Django 2.2.6 on 2019-10-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20191016_1940'),
        ('cuentas', '0004_auto_20191015_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.ruta'),
        ),
    ]
