# Generated by Django 2.2.6 on 2019-10-16 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_perfil_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='ruta',
        ),
    ]
