# Generated by Django 2.2.6 on 2019-10-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0007_perfil_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='vehiculo',
        ),
    ]
