# Generated by Django 2.2.6 on 2019-10-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0008_remove_perfil_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
