# Generated by Django 2.2.6 on 2019-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_perfil_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
