# Generated by Django 2.2.6 on 2019-11-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0011_auto_20191017_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
