# Generated by Django 2.2.6 on 2019-11-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0012_perfil_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
