# Generated by Django 2.2.6 on 2019-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=254)),
                ('fin', models.CharField(max_length=254)),
                ('usuario', models.CharField(max_length=254)),
            ],
        ),
    ]
