# Generated by Django 2.2.6 on 2019-10-16 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_rental'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
