# Generated by Django 2.2.6 on 2019-10-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20191016_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='dueno',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Ruta'),
        ),
    ]
