# Generated by Django 2.2.6 on 2019-10-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_auto_20191016_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Ruta'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Vehiculo'),
        ),
    ]
