# Generated by Django 2.2.6 on 2019-10-17 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0016_auto_20191017_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='viaje',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Viaje'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Ruta'),
        ),
    ]
