# Generated by Django 2.2.6 on 2019-11-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0031_auto_20191114_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='enCurso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.Ruta'),
        ),
    ]
