# Generated by Django 2.2.7 on 2019-11-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('justificacion', models.CharField(default='', max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(default='¿?', max_length=100)),
                ('solucion', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('bug', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Informativo.Bug')),
            ],
        ),
    ]
