# Generated by Django 2.2.7 on 2019-11-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
        ('Informativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='estado',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='bug',
            name='falla',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Eventos.Falla'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='bug',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Informativo.Bug'),
        ),
    ]
