# Generated by Django 2.2.7 on 2019-11-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='novedad',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='pregunta',
            field=models.CharField(default='¿?', max_length=100),
        ),
        migrations.AlterField(
            model_name='faq',
            name='solucion',
            field=models.CharField(default='', max_length=300),
        ),
    ]
