# Generated by Django 2.2.7 on 2019-11-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informativo', '0002_auto_20191117_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
